### ISSUE TITLE
vsm prep --stopword-file not working

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#126]
The --stopword-file flag to vsm prep doesn't seem to be working -- have tested with both Chinese and English corpora

Print statements in topic-explorer/prep.py verify that the file is read in correctly and maintained all the way through  c.in_place_stoplist(stoplist) at line 393.  But this line doesn't seem to have any effect on the corpus.

**Comment by JaimieMurdock** [comment]
Closed by 1965c331dd.

Removed the call to `unidecode` below, while keeping `word.strip()` to remove newline characters.
```python
    # Apply custom stopwords file
    if args.stopword_file:
        with open(args.stopword_file, encoding='utf8') as swf:
            candidates = [unidecode(word.strip()) for word in swf]
````
