### ISSUE TITLE
Handian corpus is saying "similarity of documents in the HandianCorpus to None"

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#132]
Document label not displayed at top of page.

**Comment by colinallen** [comment]
Line 184 of index.mustache.html says:
  {{^corpus_link}}{{corpus_name}}{{/corpus_link}} to <span class="title"></span>.</p>

How/where is docid getting inserted when there's no variable there?

**Comment by JaimieMurdock** [comment]
Being inserted [from JavaScript on L298 of www/index.mustache.html](https://github.com/inpho/topic-explorer/blob/master/www/index.mustache.html#L298):
```javascript
$('.title').html('{{doc_title_format}}'.format(title,'{{doc_url_format}}'.format(docid)));
```

format string comes from `/var/inphosemantics/Handian/HandianCorpus.ini`, which has no format string doc_title_format

**Comment by JaimieMurdock** [comment]
From `~inpho/Topics/sep/newdata.ini`

```
[www]
doc_title_format = the article on <a href="{1}">{0}</a>
doc_url_format = %(corpus_link)s/entries/{0}/
```

**Comment by JaimieMurdock** [comment]
Changing default `doc_title_format` to just `{0}` in [topicexplorer/server.py](https://github.com/inpho/topic-explorer/blob/master/topicexplorer/server.py).

**Comment by JaimieMurdock** [comment]
Changes are live: [example](http://inphodata.cogs.indiana.edu/handian/40/?doc=HandianCorpus%2F%E3%80%8E%E9%9B%86%E9%83%A8%E3%80%8F%2F%E5%B0%8F%E8%AF%B4%2F%E6%B3%AA%E7%8F%A0%E7%BC%98%2F%E7%AC%AC%E5%8D%81%E4%BA%8C%E5%9B%9E%E3%80%80%E9%9B%86%E4%B9%A6%E5%8F%A5%E5%B7%A7%E6%8B%88%E7%BA%A2%E6%A5%BC%E4%BB%A4%E3%80%80%E5%A4%BA%E9%85%92%E7%9B%8F%E7%AC%91%E6%B6%B4%E7%A2%A7%E7%BD%97%E8%A5%9F.txt)

**Comment by colinallen** [comment]
nice - thanks — I’ve merged to my chinese branch.

C.


On Jun 22, 2016, at 12:53 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


Changes are live: example<http://inphodata.cogs.indiana.edu/handian/40/?doc=HandianCorpus%2F%E3%80%8E%E9%9B%86%E9%83%A8%E3%80%8F%2F%E5%B0%8F%E8%AF%B4%2F%E6%B3%AA%E7%8F%A0%E7%BC%98%2F%E7%AC%AC%E5%8D%81%E4%BA%8C%E5%9B%9E%E3%80%80%E9%9B%86%E4%B9%A6%E5%8F%A5%E5%B7%A7%E6%8B%88%E7%BA%A2%E6%A5%BC%E4%BB%A4%E3%80%80%E5%A4%BA%E9%85%92%E7%9B%8F%E7%AC%91%E6%B6%B4%E7%A2%A7%E7%BD%97%E8%A5%9F.txt>
