### ISSUE TITLE
Train new model on Summer 2016 SEP archive

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#140]

**Comment by colinallen** [comment]
Set up quarterly cron job for 1/1, 4/1, 7/1 and 10/1.

**Comment by JaimieMurdock** [comment]
At this point, also need Fall 2016 archive modeled.

**Comment by JaimieMurdock** [comment]
Began sync of SEPMirror from `inpho.cogs.indiana.edu:/var/inpho/bin/sync_sepmirror_to_inphodata` to `inphodata.cogs.indiana.edu`

**Comment by JaimieMurdock** [comment]
Training models on inphodata for Fall 2016 archive, 1000 iterations each. 1352 total articles.

**Comment by JaimieMurdock** [comment]
New model up to date for SEP to Fall 2016: http://inphodata.cogs.indiana.edu/sep/
