### ISSUE TITLE
tutorial notebook failing

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#142]
The tutorial notebook is failing at

```
# load the topic model
v = lda_v[k]
```

with

```
/Users/colin/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.pyc in __getitem__(self, key)
    226                 return self.zip.read(key)
    227         else:
--> 228             raise KeyError("%s is not a file in the archive" % key)
    229 
    230     def __iter__(self):

KeyError: 'dtype is not a file in the archive'
```

**Comment by JaimieMurdock** [comment]
Error fixed in [inpho/vsm:292df9bd](https://github.com/inpho/vsm/commit/292df9bdd18137052a427f2effaaf59b5be4aa8d). Change will be rolled out as vsm==0.4.0b2 and topicexplorer==1.0b105. Run a `vsm update` now to get the changes on Linux and OS X, and in 10 minutes to get it on Windows.
