### ISSUE TITLE
Color bar collissions

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#145]
Topic colors still have many collisions, especially when the bars are scrambled. Previously we had implemented a graph coloring algorithm to resolve these issues, but the algorithm was NP-hard, causing immense slowdown in server launch. Also, the interim solution didn't quite fix all of the collisions.

Need to assign someone else to fix this problem - could be fun project for mathematics student.

**Comment by colinallen** [comment]
Suggestion: instead of fully solving the problem, and instead of block colors, use color gradient with saturation decreasing left to right.  At least, this way, when colors do collide, the boundaries will be very visible.

**Comment by JaimieMurdock** [comment]
Another idea that might make better use of saturation and better consistency with the topic bubble search view: only primary colors of the same hue should be used.

**Comment by JaimieMurdock** [comment]
See also #193

**Comment by colinallen** [comment]
Should be deployed to inphodata.cogs and issue closed

**Comment by JaimieMurdock** [comment]
Deployed: http://inphodata.cogs.indiana.edu/sep/20/?doc=whewell
