### ISSUE TITLE
Refactor config parsing throughout. Introduce topicexplorer.config module.

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#150]
Rather than having duplicate code in every topicexplorer submodule, create a single module that handles all config file access. Create a `Config` object that can be used throughout the application, especially in model comparison situations. Replace the `notebooks/corpus.py` template script with something that uses `Config` instead. This will massively help improve code readability.

**Comment by JaimieMurdock** [comment]
There is some config parsing code from the work @adithyant did last spring, and is already in the main branch via the code merge.

**Comment by JaimieMurdock** [comment]
This should be my weekend project for May 6-7, 2017.

**Comment by JaimieMurdock** [comment]
The goal here is to remove the `from corpus import *` and `corpus.tmpl.py` dependencies in all notebooks.

**Comment by JaimieMurdock** [comment]
I've made some good progress here on `issues/150` branch.

Below is a mockup of the  interface we're aiming for:

```python
import topicexplorer
te = topicexplorer.from_config('ap.ini')

# access the corpus with .corpus
te.corpus

# access the individual models with dictionary attributes
assert isinstance(te[k], LdaCgsViewer)
te[k].theta
te[k].phi

# comparing two models using the interface
from topicexplorer.compare import model_dist
model_dist(te[20], te[40])
```

**Comment by colinallen** [comment]
import from config is good
what happens if someone does something like this? (If I've got the syntax right:)
```
te1 = topicexplorer.from_config('tm1.ini')
te2 = topicexplorer.from_config('tm2.ini')
dist_topics_topics(te1[20][2],te2[20][2])
```
If the two tms are commensurable (same word set whether or not different corpora) it should work, but where the two tms are not really commensurable because the words don't match, do we want the mess that ensues to be on the programmer, or do we want to do something "smart"?

**Comment by colinallen** [comment]
I guess the above point should be made with the new syntax:

**Comment by colinallen** [comment]
Also, most of the syntax is perspicuous, but I find this a bit opaque:
