### ISSUE TITLE
tjmind < return to front page

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#158]
After entering at tjmind.org and clicking through to the topic explorer on either of the corpora, there's no simple way to get back to tjmind.org (e.g., if one wants to switch the corpus).

**Comment by JaimieMurdock** [comment]
**Proposed solution:** use a new config option to override header link. Default to the default index splash page.

**Comment by JaimieMurdock** [comment]
Updated TJMind corpora:
http://inphodata.cogs.indiana.edu/tjmind-proposal/
http://inphodata.cogs.indiana.edu/tjmind/

**Comment by colinallen** [comment]
both links currently 404

On Oct 6, 2016, at 10:02 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


Updated TJMind corpora:
http://inphodata.cogs.indiana.edu/tjmind-proposal/
http://inphodata.cogs.indiana.edu/tjmind/

**Comment by JaimieMurdock** [comment]
I edited post after notification:
http://inphodata.cogs.indiana.edu/tjmind-proposal/20/
http://inphodata.cogs.indiana.edu/tjmind/20/

Raw `/` links currently have no content for tjmind and tjmind-proposal so the default page is broken. I am addressing with #167
