### ISSUE TITLE
New isomap display doesn't load in Safari -- javascript error?

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#160]
http://inphodata.cogs.indiana.edu:8100 does not display correctly in Safari (main area is blank).

The Safari error console has 3 warnings and an error:

[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5)
[Error] SyntaxError: Unexpected token '>'
	(anonymous function) (inphodata.cogs.indiana.edu:246)

This is the offending line:
  var ks = data.map(d => d.k).filter(function(item, i, ar){ return ar.indexOf(item) === i; });;

Could the problem be the extra semicolon at the end of the line?

**Comment by JaimieMurdock** [comment]
Safari doesn't seem to have good ECMA 6 support so the anonymous function
declaration "d => d.k" is failing. I will use old syntax and push the
change.
