### ISSUE TITLE
term search for topics internal server error

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#171]
http://inphodata.cogs.indiana.edu/htrc1315/topics?q=comparative yields

jquery-2.2.4.min.js:4 GET http://inphodata.cogs.indiana.edu/htrc1315/topics.json?q=comparative 500 (Internal Server Error)send @ jquery-2.2.4.min.js:4ajax @ jquery-2.2.4.min.js:4n.(anonymous function) @ jquery-2.2.4.min.js:4getJSON @ jquery-2.2.4.min.js:4(anonymous function) @ pen.js:145
topics:1 Uncaught (in promise) Object {readyState: 4, responseText: "↵    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0/…l Server Error</pre>↵        </body>↵    </html>↵", status: 500, statusText: "Internal Server Error"}

**Comment by JaimieMurdock** [comment]
This is very likely due to the fact that the htrc1315 corpus and models are a legacy model from vsm 0.2, which seems to be having some type conversion errors, as evidenced by the followiing stack trace:

```python
Traceback (most recent call last):
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/topicexplorer/server.py", line 45, in set_header
    return f(*args, **kwargs)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/topicexplorer/server.py", line 318, in word_topic_distance
    query = [word for word in query if word in self.c.words]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)
```

**Comment by JaimieMurdock** [comment]
Confirmed. Old corpus does not have words as `unicode`, just regular ASCII `str`
```python
>>> from vsm import *
>>> c= Corpus.load('/var/inphosemantics/data/20130101/htrc-anthropomorphism-1315/vsm-data/hathi-1315-nltk-freq3.npz')
>>> c.words
array(['o', 'x', 'v', ..., 'christiehen', 'bisen', 'eegeneration'], 
      dtype='|S40')
>>> u'blag' in c.words
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128)
>>> u'blag'.encode('ascii', 'ignore') in c.words
False
```
