### ISSUE TITLE
term search mislabeled in explorer

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#179]
at http://inphodata.cogs.indiana.edu/handian/60/?q=%E9%98%B4%E9%98%B3

the search box at the top is labeled "Focal document" instead of "Query term" or something similar

**Comment by JaimieMurdock** [comment]
This functionality should be straight up removed from the explorer. I have completely hidden it from the interface otherwise.

It seems like we really need the long-term search indexing proposed in #135. Creating a label for all search-related issues for easy filtering later.

**Comment by colinallen** [comment]
If we remove the feature then we will have to rewrite the section of the Handian paper which relies on the feature :-(

**Comment by JaimieMurdock** [comment]
Proposed solution: If you use term search it relabels the box, but the feature is not exposed other than as a query parameter.
