### ISSUE TITLE
re-retrain of Chinese corpus fails with "unsupported corpus dtype and topicdtype" error

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#182]
Originally trained HandianCorpus for 200 cycles.  Can retrain that once, but then second retraining fails as shown below, with "Unsupported corpus dtype (uint32) and topic dtype (<type 'numpy.uint8'>) combination" -- have tried this twice.  

'''
Existing topic models found. You can continue training or start a new model. 
Do you want to continue training your existing models?  [Y/n] 
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz

Total number of training iterations: [Default: 450] 1000

TIP: number of training iterations can be specified with argument '--iter N':
         topicexplorer train --iter 1000 HandianCorpus.ini

Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
Continue training 20-topic model (300 => 1000 iterations)
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/topicexplorer", line 9, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 218, in main
    benchmark(train.main)(args)
  File "/Users/colin/topicexplorer/topicexplorer/train.py", line 178, in main
    dry_run=args.dry_run)
  File "/Users/colin/topicexplorer/topicexplorer/train.py", line 59, in continue_training
    m.train(n_iterations=total_iterations - orig_iterations)
  File "/Users/colin/anaconda/lib/python2.7/site-packages/vsm/model/ldacgsseq.py", line 178, in train
    self.corpus.dtype, self.Ktype))
NotImplementedError: Unsupported corpus dtype (uint32) and topic dtype (<type 'numpy.uint8'>) combination

**Comment by JaimieMurdock** [comment]
Interesting and very strange that this only happens AFTER two retrains. The unsupported type errors point to a problem in the second serialization. Fortunately the unit tests show that the results are not diverging after the first retrain. I'll look into this later this afternoon.

**Comment by colinallen** [comment]
Another weird thing I’ve noticed (but may be unrelated) is that on launch, all the [retrained]  models seem to be read twice…

140-182-73-16:~/corpora/Chinese/Handian] colin% topicexplorer launch HandianCorpus.ini
using default label function
using default id function
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K40-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K40-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K60-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K60-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K80-document-300.npz
Loading LDA data from /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K80-document-300.npz
TIP: Browser launch can be disabled with the '--no-browser' argument:
topicexplorer serve --no-browser HandianCorpus.ini


On Nov 30, 2016, at 11:02 AM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting and very strange that this only happens AFTER two retrains. The unsupported type errors point to a problem in the second serialization. Fortunately the unit tests show that the results are not diverging after the first retrain. I'll look into this later this afternoon.

**Comment by JaimieMurdock** [comment]
That is even weirder - can you upload your HandianCorpus.ini? I have a hypothesis that the k values are being doubled, pointing to an error in `topicexplorer.init`

**Comment by colinallen** [comment]
Here's the ini file...

[DEFAULT]
sentences = False
htrc = False

[main]
path = /Users/colin/corpora/Chinese/Handian/models
corpus_file = /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000.npz
raw_corpus = /Users/colin/corpora/Chinese/Handian/HandianCorpus
sentences = False
lang = cn
corpus_desc = HandianCorpus.ini.md
model_pattern = /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K{0}-document-300.npz
context_type = document
topics = [20, 40, 60, 80]
cluster = /Users/colin/corpora/Chinese/Handian/models/HandianCorpus-freq5-nltk-en-freq5-N300000-cluster.csv

[www]
corpus_name = HandianCorpus
icons = fingerprint,link
fulltext = false

[logging]
path = logs/HandianCorpus/{0}.log

**Comment by colinallen** [comment]
And here's a listing of the models directory. (Note that "Old" is where I stashed the previous models.)



HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-200.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K20-document-300.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K40-document-200.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K40-document-300.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K60-document-200.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K60-document-300.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K80-document-200.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-LDA-K80-document-300.npz
HandianCorpus-freq5-nltk-en-freq5-N300000-cluster.csv
HandianCorpus-freq5-nltk-en-freq5-N300000.npz
HandianCorpus-freq5.npz
Old

**Comment by JaimieMurdock** [comment]
Was this ever resolved or can it be replicated? Trying to purge issue tracker and triage.
