### ISSUE TITLE
wrong document appearing in search box after delay

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#186]
No matter which document is chosen in handian, the search box is populated with this one, after a delay of 2-3 seconds on inphodata, up to 30 secs on inpho.xjtu: 
    HandianCorpus/『史部』/传记/列女传/卷之一　母仪传.txt

e.g. 
http://inphodata.cogs.indiana.edu/handian/40/?doc=HandianCorpus%2F%E3%80%8E%E5%AD%90%E9%83%A8%E3%80%8F%2F%E6%B3%95%E5%AE%B6%2F%E6%A3%A0%E9%98%B4%E6%AF%94%E4%BA%8B%2F%E6%BF%82%E6%BA%AA%E6%82%9F%E9%85%B7.txt

http://inpho.xjtu.edu.cn/handian/40/?doc=HandianCorpus%2F%E3%80%8E%E5%AD%90%E9%83%A8%E3%80%8F%2F%E6%B3%95%E5%AE%B6%2F%E6%A3%A0%E9%98%B4%E6%AF%94%E4%BA%8B%2F%E6%BF%82%E6%BA%AA%E6%82%9F%E9%85%B7.txt

**Comment by colinallen** [comment]
Also, reloading the topic model with a different value for k uses the actual focal document rather than what's showing in the query box.

**Comment by JaimieMurdock** [comment]
Appears to be fixed.
