### ISSUE TITLE
Not all single-depth trees are books/pages

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#192]
When processing an unbalanced or multi-level tree (such as Handian), the init step defaults to document mode, and fulltext serving is seamless after launch. But when processing a folder of folders all containing files, the user is prompted with BOOK/page choice (as if htrc structure) and if 'page' is chosen, the hypershelf shows only numbers instead of path/filenames, and doesn't show documents.  Should be a third option that handles this case just like a multi-level tree.

**Comment by JaimieMurdock** [comment]
Context types in general could use more description, it would be nice to spec out what the possiblities are and enable some sort of UI to specify them.

**Comment by colinallen** [comment]
Right, but just adding 'document' as an option when BOOK/page options are given may cover most of the cases. Perhaps it should be DOCUMENT/book/page as the default.

**Comment by JaimieMurdock** [comment]
Related to #95

**Comment by JaimieMurdock** [comment]
Contexts will no longer exist - might add a prompt just to get naming right, but just replacing with "document" for now.
