### ISSUE TITLE
Match topic bubble colors and topic bar colors

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#193]
From Tassie Gnaidy - match the topic bubble colors to the topic bar colors. With any luck this will also help the topic color collision issues

**Comment by colinallen** [comment]
Interesting suggestion - but so we should have as many bubble clusters as there are distinct colors?

On Mar 8, 2017, at 3:01 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


From Tassie Gnaidy - match the topic bubble colors to the topic bar colors. With any luck this will also help the topic color collision issues
