### ISSUE TITLE
`ap.tgz` no longer downloads from Blei's site

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#196]
1) We can probably find a better source to test for the `topicexplorer demo` command (SEP sub-set, perhaps?)
2) For now, I can rehost `ap.tgz` on an inpho server as a permanent resource, and change the URL in topicexplorer/demo.py

**Comment by colinallen** [comment]
I think a SEP subset would be good for 1.  Do we need to ask David Blei for 2?  Who owns that dataset?

On Mar 28, 2017, at 1:39 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  We can probably find a better source to test for the topicexplorer demo command (SEP sub-set, perhaps?)
  2.  For now, I can rehost ap.tgz on an inpho server as a permanent resource, and change the URL in topicexplorer/demo.py

**Comment by JaimieMurdock** [comment]
His institutional affiliation change from Princeton -> Columbia is finally final, so his Princeton site was removed. I found the site moved to http://www.cs.columbia.edu/~blei/lda-c/

The dataset itself is a subset of the TREC-AP corpus. The whole corpus is copyright, but this subset has been released for testing with LDA.

**Comment by JaimieMurdock** [comment]
Regarding the SEP subset -- we should have a discussion about archival and machine learning for the SEP and archives. It's the data underlying the InPhO Project, but it would be nice to make a more easily accessible archive for other projects to use with clear licensing. I think the biggest is that we'd have to do some sort of non-consumptive research policy.

Perhaps a topic for another repo or issue - I'll discuss with you as part of the "what's next" conversation in April/May.
