### ISSUE TITLE
Error with spaces in filename on Windows

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#197]
On attempting to run "topicexplorer notebook TJCombo.ini” we get:

```
IOError: [Errno 22] invalid mode ('rb') or filename: '"C:/Users/Aish Thamba/Downloads/TJ All/models/TJCombo-freq5-freq5-N20000.npz”’
```

**Comment by JaimieMurdock** [comment]
Kirtan, would you mind trying to create a bug like this by creating a folder with a space in the name and trying to run `topicexplorer init "Name of the New Folder with Spaces"` on it?

**Comment by kirtansakariya** [comment]
Hi Jaimie, I ran it on a folder with spaces in it and it gave me an error: UnicodeDecodeError: 'utf8' codec can't decode byte 0xd2 in position 15: invalid continuation byte
I have 7 files in the folder and they are all word documents. I was thinking that maybe it was an issue with the files so I removed them and ran it on an empty folder but that gave me this error: AttributeError: 'functools.partial' object has no attribute '__name__'

**Comment by JaimieMurdock** [comment]
It definitely won't work on word documents, as it doesn't have support 
for that file type yet. Strange that it didn't raise an error about that.

Then strange again that it didn't work with an empty folder. Would you 
mind taking a screenshot of the terminal window with the command visible 
next time you run it?

**Comment by JaimieMurdock** [comment]
Closing again
