### ISSUE TITLE
Migrate pdfminer to PyPDF2, which has better Py2+3 support

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#201]
https://github.com/mstamy2/PyPDF2

**Comment by JaimieMurdock** [comment]
Work on this was started, but we don't have a good test corpus for PDFs to try it on. Need to develop small corpus for download and try -- maybe I'll just use the revisions of the Darwin paper? Nice and confounded. http://arxiv.org/abs/1509.07175

https://github.com/inpho/topic-explorer/commit/fbf59c753588a15c1e8d75c28b6b7d579c2211a8

**Comment by colinallen** [comment]
Somewhere I have a PDF corpus of my own papers — may be more heterogenous than the Darwin versions?

**Comment by JaimieMurdock** [comment]
I ended up using `pdfminer.six` rather than switching to PyPDF, but this is done! Yay!
