### ISSUE TITLE
Mac OS Update has broken launch to browser (and Jupyter)

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#205]
0:62: execution error: "http://140-182-73-82.ssl-vpn.indiana.edu:8000/" doesn’t understand the “open location” message. (-1708)

https://github.com/jupyter/notebook/issues/2438 for details and possible solutions

**Comment by colinallen** [comment]
Looks like it's an Apple bug that will get resolved with the next OS X release: http://www.andrewjaffe.net/blog/2017/05/python-bug-hunt.html

**Comment by JaimieMurdock** [comment]
Hopefully next minor release, and not major release. That's very
disappointing.

We will need to fix more immediately for user support though. Lots of
people on Macs.

**Comment by colinallen** [comment]
Setting browser in shell rc file works as a temporary fix (using Chrome as example):

e.g., .bashrc
BROWSER=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
export BROWSER

or .cshrc
setenv BROWSER /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome


On Jun 23, 2017, at 10:57 AM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:

Hopefully next minor release, and not major release. That's very
disappointing.

We will need to fix more immediately for user support though. Lots of
people on Macs.

**Comment by JaimieMurdock** [comment]
Easy fix is to add `jupyter notebook --browser=Chrome` to command - the trick will be pinging to find the default browser.

**Comment by colinallen** [comment]
Default browser is kept (I think) in  ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist

There’s a python lib for reading plist files: https://docs.python.org/2/library/plistlib.html



On Jun 23, 2017, at 11:38 AM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


Easy fix is to add jupyter notebook --browser=Chrome to command - the trick will be pinging to find the default browser.

**Comment by JaimieMurdock** [comment]
Fixed in macOS 10.12.6, which was released on July 17, 2017 https://support.apple.com/en-gb/HT207835
