### ISSUE TITLE
docs.json file very large, causes slow performance

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#206]
inphodata.cogs.indiana.edu/handian/docs.json returns a 7.7 MB file used for autocompletion of file names.  This is excessively slow (especially in China, even using the inpho.xjtu mirror).  Is there some way to make it more efficient?

**Comment by JaimieMurdock** [comment]
Wow. That's really really intense - it should only return a partial list 
of names based on a query. I can make sure the whole docs.json isn't 
returned.

Another fix would be to implement some sort of html5 localStorage 
solution that would help with caching of these partial results.
