### ISSUE TITLE
gpu error on notebook launch

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#209]
using ap demo corpus on mac w/Chrome: 

topicexplorer notebook ap.ini
...
[37396:32771:0818/075811.928354:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

Notebooks seem to run ok, though

**Comment by JaimieMurdock** [comment]
Not an error with topic explorer - that's a message from your browser.
