### ISSUE TITLE
demo/fulltext not working / Python3

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#216]
File “/Users/colin/anaconda/bin/bottle.py”, line 862, in _handle
    return route.call(**args)
  File “/Users/colin/anaconda/bin/bottle.py”, line 1740, in wrapper
    rv = callback(*a, **ka)
  File “/Users/colin/topicexplorer/topicexplorer/server.py”, line 64, in set_header
    return f(*args, **kwargs)
  File “/Users/colin/topicexplorer/topicexplorer/server.py”, line 489, in get_doc
    doc_id = doc_id.decode(‘utf-8’)
AttributeError: ‘str’ object has no attribute ‘decode’

Python 3 doesn’t use decode any more, so I think we need to add: if P2, decode, if P3 not.

**Comment by colinallen** [comment]
Added to server.py line 494:

          try:
                doc_id = doc_id.decode('utf-8')
            except AttributeError:
		# do nothing                                                    
		doc_id = doc_id

But this brings up a new error:
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/colin/anaconda/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/Users/colin/topicexplorer/topicexplorer/server.py", line 64, in set_header
    return f(*args, **kwargs)
  File "/Users/colin/topicexplorer/topicexplorer/server.py", line 498, in get_doc
    if os.path.exists(os.path.join(corpus_path), doc_id + '.txt'):
TypeError: exists() takes 1 positional argument but 2 were given

Another P3 differences?

**Comment by JaimieMurdock** [comment]
Fixed
