### ISSUE TITLE
Hypershelf is attempt to display pdf instead of mined txt

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#220]
Python 3 with pdfminer --

Ran topicexplorer over a bunch of pdfs but it's defaulting to .pdf file names and after launch with --fulltext, it’s attempting to render the pdfs in the overlay panel.

![image](https://user-images.githubusercontent.com/705195/31591601-307fe026-b1ef-11e7-9ffe-2dca77ef8900.png)

**Comment by colinallen** [comment]
Should this issue be closed?

**Comment by JaimieMurdock** [comment]
Merged.
