### ISSUE TITLE
Help not working

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#224]
Help button does nothing in topic explorer

**Comment by kirtansakariya** [comment]
When inspecting the help button using the developer tools in chrome, an error would popup every time help was clicked. The error said that "togglesearch is not defined." I believe togglesearch is being called from line 51 in master.mustache.html. Maybe for now, replacing help with a static popup would suffice, but later a more dynamic help button would be better to have?

**Comment by colinallen** [comment]
I think that we should probably use the same modal style as the (c) link and develop text for each page to fill the modal. 

So, instead of 
‘’'
<a class="selected" data-placement="right" title="" href="javascript:toggleSearch()" data-original-title="Help"><strong>?</strong></a>
‘’'

It should look like
‘''
<a href="#" class="selected" data-placement="right" title="" data-toggle="modal" data-target="#rightsModal" data-original-title="Usage"><strong>©</strong></a>
‘’'

In the long run, though, we should pursue some ideas that Jaimie had about a dynamic tutorial, i.e.: (Quoting Jaimie) Add a &tutorial=1 flag to the topic explorer URLs that creates a guided tutorial like athttp://stacklife.harvard.edu/explainer.php <http://stacklife.harvard.edu/explainer.php>. Use this tutorial from the main splash page.

**Comment by JaimieMurdock** [comment]
I've spent some time with the text on the help pages.

The following pages need functional help buttons now:
- [x] Hypershelf page
- [ ] Main page
- [ ] Cluster page

**Comment by colinallen** [comment]
Is this back to Kirtan to push the code?

**Comment by colinallen** [comment]
I have updated help-topics.md but it is not being loaded at http://inphodata.cogs.indiana.edu/oldbailey/topics

**Comment by JaimieMurdock** [comment]
Issue is that help paths are relative, not absolute, did a hand patch on bars and master page, but not cluster. Something like `$.get('/help-topics.md', ...)`
