### ISSUE TITLE
demo fail nltk

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#225]
Fresh developer install on new laptop with Python 3
topicexporer demo gets to training stage fails after writing corpus & ini file with:

ERROR: stopwords not available, download by running:
    python -m nltk.downloader stopwords

**Comment by JaimieMurdock** [comment]
very strange that it does not fail most recent test: https://travis-ci.org/inpho/topic-explorer/jobs/288355735

by fresh install, do you mean all the way to cloning the repo via `pip` as documented in the `README`? 

`pip install --src . -e git+https://github.com/inpho/topic-explorer#egg=topicexplorer`

**Comment by colinallen** [comment]
Yes, that's correct.  It was a completely fresh install on a new machine.

**Comment by JaimieMurdock** [comment]
It's strange that as the software checks for this error and gives the right command to run, it doesn't just call `nltk.download('stopwords')` and try again.

The issue appears to be with `PostInstallData` in `setup.py` not firing: https://github.com/inpho/topic-explorer/blob/master/setup.py#L32

**Comment by JaimieMurdock** [comment]
I'm not sure I can replicate this error. Going to close Wednesday if not.

**Comment by colinallen** [comment]
I haven't replicated it, but I just tried another "clean" developer install in a separate account on my laptop with Python3, and it failed as shown:


Downloading vsm-0.4.1.tar.gz (225kB): 225kB downloaded
  Running setup.py (path:/private/var/folders/05/gzrqjsr88xjc0n001s7mpc5r0000gr/T/pip_build_colallen/vsm/setup.py) egg_info for package vsm
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/05/gzrqjsr88xjc0n001s7mpc5r0000gr/T/pip_build_colallen/vsm/setup.py", line 5, in <module>
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/05/gzrqjsr88xjc0n001s7mpc5r0000gr/T/pip_build_colallen/vsm/setup.py", line 5, in <module>

    from Cython.Build import cythonize

ImportError: No module named Cython.Build

**Comment by JaimieMurdock** [comment]
This is due to `vsm 0.4.1` not having a Mac build uploaded - it's a minor patch on `vsm 0.4.0`. I need to set you up with PyPI uploding privileges so you can compile and get this fixed permanently. `inphodev` appears to still be down. 

If I had ssh access to a Mac, I could do it myself.

**Comment by JaimieMurdock** [comment]
Fixed and uploaded new version of vsm to pypi
