### ISSUE TITLE
Loading Page

### ISSUE THREAD

**Issue by kirtansakariya** [inpho/topic-explorer#226]
For machines that are slow to launch topicexplorer, it would be nice to have an indicator that something is happening such as a load animation.

**Comment by JaimieMurdock** [comment]
Just to make sure - this is an indicator for the cluster page or the topic bars page?

If the topic bars page, that indicator is already there.

For the cluster page, this is a bit of a problem that might be worth changing the request cycle for `cluster.csv`: right now if the clusters have already been computed, then they are simply returned with an `HTTP 200 OK` status. However, if they have not been computed, the request blocks - meaning that no status code is returned until the computation is complete.

A better request cycle might be offered by the `HTTP 100` status code: http://www.kansas.com/news/politics-government/article154684809.html

In this request cycle, the `GET` request would send a `Expect: 100-continue` header and receive the data `100 Continue` before the `cluster.csv` data is eventually sent. This would enable the loading bar to start spinning. If an error occurred (for example a `500 Internal Server Error`), then proper error handling could handle the request.

**Comment by colinallen** [comment]
Kirtan and I discussed this last week and we could not replicate the slow loading on his laptop that had prompted this -- but basically it was for the splash page that comes up first when doing 'launch'.  It may have had something to do with the hostname problem; meanwhile, we decided to mothball this issue.
