### ISSUE TITLE
topicexplorer init not working on folder of pdf files

### ISSUE THREAD

**Issue by kirtansakariya** [inpho/topic-explorer#229]
When trying to topicexplorer init on a folder of pdf files, I keep getting an error that halts the process.
<img width="1440" alt="screen shot 2017-11-21 at 2 03 30 pm" src="https://user-images.githubusercontent.com/9168349/33092270-a52fe958-cec7-11e7-81f5-9475812bc7d2.png">

I tried surrounding the folder name with quotes as well, but that did not work either.

**Comment by JaimieMurdock** [comment]
The issue was caused by issues with bytes/string encoding in the migrated Python 3 packages. Now works with support for both Py2 and Py3 a of `1.0b187`
