### ISSUE TITLE
Ambiguity in hypershelf display

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#240]
The image below shows the top documents for topic 13 (note URL and position of 13 at top left of the key) after they have been re-sorted for proportion of topic 12.  The blue button saying "Top documents for topic 12" will look to some users like a label rather than an option to fetch a different set of documents.  Need to change label of the button to say "Retrieve top docs...." and perhaps also add a title to say what the current search state is.

![image](https://user-images.githubusercontent.com/705195/34774125-2c6e1e68-f5dc-11e7-81a3-cd82a2a73eaa.png)

**Comment by JaimieMurdock** [comment]
Good ideas!

**Comment by colinallen** [comment]
closed by #249
