### ISSUE TITLE
HTRC-1315 collection not loading (book_label error)

### ISSUE THREAD

**Issue by kirtansakariya** [inpho/topic-explorer#241]
The topicbars for the HTRC-1315 collection are not loading due to a book_label error. The error can be found at this link: http://inphodata.cogs.indiana.edu/htrc1315/80/?doc=yale.39002085618560.

**Comment by colinallen** [comment]
currently running `topicexplorer metadata -l /tmp/htrc_ids /var/www/topicexplorer/config/htrc1315.ini && htrc metadata /tmp/htrc_ids > metadata.json` on inphodata.cogs to see if it fixes error

**Comment by JaimieMurdock** [comment]
Closed - was both an issue with `topicexplorer.extensions.htrc` and the actual metadata file for that collection.
