### ISSUE TITLE
Access contents of documents

### ISSUE THREAD

**Issue by bricksdont** [inpho/topic-explorer#246]
Hi,

I have trained topic models with topicexplorer and can launch them. However, I cannot find a way to access the original text of the documents.

The help text of the hypershelf says: 

> Other icons to the left of each topic bar allow you to view the document contents,

but I cannot find such an icon.

Interestingly, this is available as an icon in the AP demo here:

http://inphodata.cogs.indiana.edu/ap/

What do I need to change to be able to view the document text itself?

Thanks a lot.

P.S. More generally, is there more help / documentation about this software? For instance, I would like to know

- how exactly I can supply my own list of stopwords for a different language
- what "context" means when I am asked about BOOK/pages during training

**Comment by colinallen** [comment]
Hi Mathias — you should launch the topicexplorer with the --fulltext option to enable those links.

**Comment by bricksdont** [comment]
Thanks Colin!

Is there documentation about this - that I can read without having to bother you?

**Comment by JaimieMurdock** [comment]
Hi @bricksdont,

In general each command has help available with a `-h` flag (e.g., `topicexplorer prep -h`).

To answer your question about supplying your own list of stopwords `topicexplorer prep --stopword-file FILENAME` should do what you would like. There are several stoplists included from `nltk`, but they may not be well suited to your purposes.

For the "context" question, that's some leftover work from a [research project on the HathiTrust](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0184188). The book/pages distinction corresponds to folders and files when training on a collection that is organized as a series of folders with files in each folder. Using "book" means that all files in each folder are treated together as a single document. Using "pages" means that each file in each subfolder is its own document.

Let us know if you have any more questions, documentation is a big next push. We both switched affiliations this year, so energy has been focused on redeploying services to cloud providers. That's delayed a comprehensive 1.0 release and questions help us know more about usage patterns!

**Comment by bricksdont** [comment]
Thanks Jamie for the swift and helpful replies!
Closing for now.
