### ISSUE TITLE
`--fulltext` option yields "No option 'pdf' in section: 'www'"

### ISSUE THREAD

**Issue by bricksdont** [inpho/topic-explorer#248]
I'm trying to serve the full-text documents. Using `--fulltext` brings up the following error:

```sh
$ topicexplorer launch data.ini --fulltext
```
```python
Traceback (most recent call last):
  File "/Users/mathiasmuller/miniconda2/bin/topicexplorer", line 11, in <module>
    sys.exit(main())
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/topicexplorer/__main__.py", line 242, in main
    app = benchmark(server.create_app)(args)
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/topicexplorer/server.py", line 678, in create_app
    if (config.getboolean('www', 'pdf')):
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 849, in getboolean
    **kwargs)
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 822, in _get_conv
    return self._get(section, conv, option, **kwargs)
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 814, in _get
    return conv(self.get(section, option, **kwargs))
  File "/Users/mathiasmuller/miniconda2/lib/python2.7/site-packages/backports/configparser/__init__.py", line 803, in get
    raise NoOptionError(option, section)
backports.configparser.NoOptionError: No option 'pdf' in section: 'www'
```
This happens on both Mac OS X and Windows 10.

Does not seem like a lethal error, but maybe you're faster than me to spot what's wrong?

Thanks for your help!

**EDIT**: I think this is because in `init.py`, here:

https://github.com/inpho/topic-explorer/blob/master/topicexplorer/init.py#L359

it's possible for "pdf" in "www" not to be set at all, if the `if` statement does not evaluate to true. Also, it's strange that this seems to set a boolean, but as a string. Why is that?

**Comment by colinallen** [comment]
This looks like a version problem as we recently did some upgrades that enhanced handling of pdfs.  Can you check the version number with ‘topicexplorer version’ ?   I am on 1.0b192 and the pdf handling works fine.

There’s a quick fix you should be able apply, however:

In your corpus ini file, you should have section that looks like this

[www]
corpus_name = [YOUR_CORPUS]
icons = fingerprint,link
fulltext = false
pdf = true

If you ensure that you have fulltext = false and pdf = true there it should work.  Note that this should be set up correctly if you init the corpus from a folder of pdf files.

**Comment by bricksdont** [comment]
I'm initializing from a corpus of *.txt files. What's the correct setup in this case?

```
$ topicexplorer version
1.0b192
```

**Comment by JaimieMurdock** [comment]
```
[www]
corpus_name = [YOUR_CORPUS]
icons = fingerprint,link
fulltext = false
pdf = false
```

**Comment by colinallen** [comment]
ah, ok then the pdf option should not apply.  From txt files the fulltext flag should be set to True and pdf flag should be False (or absent, but maybe we introduced a bug, so we’ll investigate that)

**Comment by bricksdont** [comment]
Thanks! Now I do not get an error anymore. I can launch the web interface, and for each document, it seems like the leftmost icon gives you the full text. But, clicking on it does nothing.

During training, asked about "contexts", I selected "BOOK", is that a problem with the full text?

Tell me if you need more information to debug.

**Comment by JaimieMurdock** [comment]
I think for the fulltext, given how your corpus is structured, you must train with the PAGES context. 

I've only tested that feature with corpora that consist of a single folder with files, but based on the code we have it should work.

**Comment by bricksdont** [comment]
Works with PAGES context or flat folder with files.
Thanks for all the help!

P.S. Minor: the icon for fulltext does not have a mouseover tooltip right now

Closing this issue soon.
