### ISSUE TITLE
`pip install topicexplorer` does not run `install_data` step

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#252]
pip 9.0.1 does not run the `install_data` step post install on Windows 10. 

This means that the `nltk` datasets for stoplisting and tokenizing are not downloaded.

 A temporary solution is to run `python setup.py install_data` but that will only work for develop installs with full source code.

**Comment by JaimieMurdock** [comment]
Big question is whether to run the nltk checks at runtime in `topicexplorer init` or on any `topicexplorer` command, including `version`. Right now I have it as `init`.

**Comment by colinallen** [comment]
I guess the sooner we detect it’s missing the better, so on all commands...
