### ISSUE TITLE
stoplisting/filtering not working

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#262]
I just prepped and trained a model with min-word-length 4 and using a custom stoplist

word search within the topics correctly reports words as stoplisted, but the topics themselves contain stoplisted words -- e.g. 'air' in the attached image

<img width="1440" alt="untitled" src="https://user-images.githubusercontent.com/705195/36600561-9ee3abea-1880-11e8-9f1e-3eac46201864.png">

**Comment by colinallen** [comment]
Never mind -- this seems to have been a cache issue

**Comment by JaimieMurdock** [comment]
There is definitely a need to force cache refreshes though, and we can do that by implementing E-Tags for our content: https://en.wikipedia.org/wiki/HTTP_ETag

**Comment by JaimieMurdock** [comment]
Filed an issue for ETags: #263
