### ISSUE TITLE
Add documentation for label change to metadata module.

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#264]
A model was trained on a set of docs, a small percentage of which were mislabeled at the source, but which have since been corrected at the source.  I don’t want to retrain the model.  How do I change the labels?  I understand that they are available from the corpus load as ctx_metadata, where each item is an (id,label) pair.  I can change that data structure, but how to write it back out to the npz files in a such a way that nothing else breaks?

**Comment by JaimieMurdock** [comment]
This mostly needs documentation on the metadata module. Changing bug name to reflect that.
