### ISSUE TITLE
chinese.py in Python3

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#265]
Chinese tokenizers zh and ltc are failing in python3 because of
```
  ...chinese.py", line 67, in <module>
    for a in string.lowercase[:],string.uppercase[:],range(0,10):
```
Python3 uses string.lower and string.upper instead.  How do we code this to make sure it works in both 2 and 3?

**Comment by colinallen** [comment]
Actually, it's more complicated than this. In P3, upper() and lower() are methods to use on strings.  But in chinese.py we want a piece of the string.lowercase and string.uppercase data, so it's something else that has to happen than changing [x]case to [x].

**Comment by colinallen** [comment]
Ok -- we need to uncomment previous line and then use ascii_lowercase and ascii_uppercase instead, but now a new problem:

**Comment by colinallen** [comment]
But now a new problem:
```
  File "/Users/colin/topicexplorer/topicexplorer/init.py", line 297, in main
    sentences=args.sentences, tokenizer=args.tokenizer)
  File "/Users/colin/topicexplorer/topicexplorer/init.py", line 185, in build_corpus
    from topicexplorer.lib.chinese import modern_chinese_tokenizer
  File "/Users/colin/topicexplorer/topicexplorer/lib/chinese.py", line 69, in <module>
    chinese_punctuation.append(str(b).decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by colinallen** [comment]
Previous can be fixed by removing all decode calls, but now it fails at mmseg:

**Comment by JaimieMurdock** [comment]
just remove the `decode` all of these issues seem to be related to the python 2/3 unicode disambiguation.

Some notes on strings and bytes: http://python-future.org/compatible_idioms.html#strings-and-bytes

**Comment by colinallen** [comment]
Attempting to install mmseg fails with
```
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fm/8mtkd0vd46x6609v5d4ht1q80000gp/T/pip-build-lz61wbs7/mmseg/
```

**Comment by colinallen** [comment]
Tried updating pip setuptools as suggested at https://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c but still getting the error
```
Collecting mmseg
  Using cached mmseg-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fm/8mtkd0vd46x6609v5d4ht1q80000gp/T/pip-build-yyhwt5c7/mmseg/setup.py", line 6, in <module>
        reload(sys)
    NameError: name 'reload' is not defined
```

**Comment by colinallen** [comment]
Looks like mmseg may not be P3 compatible

**Comment by JaimieMurdock** [comment]
mmseg is most definitely not P3 compatible.

**Comment by JaimieMurdock** [comment]
I've made some significant progress on this at https://github.com/inpho/mmseg. 

I'd feel better if this package had some unit tests.

**Comment by colinallen** [comment]
I gave @kirtansakariya  two small corpuses, on in modern Ch and other in ancient Ch and outlined the steps to take.  I have just invited him to join inpho/mmseg repository, but I also feel like we need an open issue here so that it can be on the 1.0 milestones list.

**Comment by JaimieMurdock** [comment]
Should be good now.
