### ISSUE TITLE
Python 2>3 compatibility of npz

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#266]
Currently Py3 fails when loading corpus/models created with Py2.  At all steps of topicexplorer, when a mismatch is detected, user should be given option to upgrade to Py3 or abort.

Py3 can load Py2 npy or npz pickle files with the command shown here, documented at
https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html
```
numpy.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')[source]
Load arrays or pickled objects from .npy, .npz or pickled files.

Parameters:    
...
encoding : str, optional

What encoding to use when reading Python 2 strings. Only useful when loading Python 2 
generated pickled files in Python 3, which includes npy/npz files containing object arrays. 
Values other than 'latin1', 'ASCII', and 'bytes' are not allowed, as they can corrupt numerical data.
Default: 'ASCII'
```

**Comment by JaimieMurdock** [comment]
How is this for an interaction pattern?

```
$ topicexplorer launch py2model.ini
Error: Trying to launch Python 2 model in Python 3. Convert using topicexplorer upgrade py2model.ini
$ topicexplorer upgrade py2model.ini 
New filename: py3model
$ topicexplorer train py3model.ini
...
```

**Comment by colinallen** [comment]
Right — I don’t think we need to provide the down-grade route.

**Comment by JaimieMurdock** [comment]
Can just load Python 2 objects now without even doing an explicit convert step, will push out with next release.
