### ISSUE TITLE
Modularization of JS code

### ISSUE THREAD

**Issue by kirtansakariya** [inpho/topic-explorer#284]
The JavaScript code is spread throughout the HTML files. It might be a better idea to just merge it into the already existing JavaScript files.

Already attempted this one before, but there were numerous issues. Going to try it one more time and do thorough tests after every one or two functions are copied over.

**Comment by JaimieMurdock** [comment]
@kirtansakariya, is there anything else before this issue is closed? I merged the first pull request and seem to remember you mentioning there might be another.

**Comment by kirtansakariya** [comment]
@JaimieMurdock Oh yeah. So I ended up making a pull request for cluster and splash (which was the first half). Moving the JS code from bars was the other thing that I was talking about. I was thinking that this would be merged before I finished bars but I ended up finishing bars earlier than I thought I would. So this issue should be good to be closed now.

Only thing that I'm concerned about is whether or not I handled the cookies properly, so if I would prefer if you were able to look at that.

**Comment by JaimieMurdock** [comment]
Just made a minor correction to fix cookie expiration in https://github.com/inpho/topic-explorer/commit/2ceb1123684c4d9d058e11c32e10084d11ec6f01

document.cookie can take either `max-age` or `expires` to determine when they expire. I just used `max-age`: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
