### ISSUE TITLE
corpus.py load fail in tutorial notebook with 1.0b200

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#286]
```
from corpus import *
  File "/Users/colin/corpora/notebooks/corpus.py", line 50
    print topic_range
                    ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by JaimieMurdock** [comment]
I'm rather confused here, as ipynb/corpus.tmpl.py, which generates notebooks/corpus.py has had `print(topic_range)` for [nearly 11 months](https://github.com/inpho/topic-explorer/blame/master/ipynb/corpus.tmpl.py#L60). 

Is this an old corpus.py? Would it be possible an old version of corpus.tmpl.py is cached somewhere in the environment?

**Comment by colinallen** [comment]
Yes, possible. But I thought pip install should make sure everything is up to date.  

Also,

 -rw-r--r--  1 colin  staff  2071 Mar 21 17:31 ipynb/corpus.tmpl.py

So that’s just a few days old.

C.

**Comment by colinallen** [comment]
Ah, ok, I found the problem, an older Tutorial file with spaces resided in the same directory as the new one, and I had just clicked on the first:

```
