### ISSUE TITLE
SEP model confusion

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#287]
Somehow the SEP topic modeling has confused 'concepts' (see fingerprint at https://www.inphoproject.org/idea/1734)  with 'concepts-god' (https://www.inphoproject.org/idea/1583).  This is consistent across all values of K, so seems to be due to something wrong at the init stage, or perhaps in the metadata?

**Comment by JaimieMurdock** [comment]
Maybe a bad split on '-'?

**Comment by colinallen** [comment]
No, I did nothing to the labels

**Comment by JaimieMurdock** [comment]
My current hypothesis: A document did not parse correctly but was not removed from the metadata, so there is an off-by 1 error in all subsequent articles.

**Comment by colinallen** [comment]
To find out how many are affected, and help track down here the trouble began it should be possible to run a comparison of the sep dirs to the titles via the InPhO entities, right?

**Comment by colinallen** [comment]
All seems good now in the spring 2018 model, so closing this.
