### ISSUE TITLE
Strange behavior on macOS on Pitt eduroam network

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#296]
For some reason connections to pypi aren't working on Pitt's eduroam network, but are working on the other networks. 

I made a comment thinking it was related to a network protocol here, and there is a suggestion on a few things to try: https://github.com/pypa/pip/issues/1182

**Comment by colinallen** [comment]
The issue here is related to this: https://github.com/pypa/pypi-legacy/issues/587 <https://github.com/pypa/pypi-legacy/issues/587>

**Comment by colinallen** [comment]
I believe this may have been due to the same issue as #261 -- ipv6 config needs to be set to Link local
We are not sure we can replicate fully but will mark as closed for now.
