### ISSUE TITLE
No metadata

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#30]
When there's no metadata associated with a document, the tooltip should indicate that fact. (Current examples are German lang docs in Darwin/HTRC corpus.)

**Comment by JaimieMurdock** [comment]
Need to add data-dependencies to icons - if no data, show a blank icon. Bug has been open for 2 years, embarassingly.

**Comment by colinallen** [comment]
This may be rendered moot by the fact that we have disabled the metadata panel for HTRC docs

**Comment by JaimieMurdock** [comment]
Good point.
