### ISSUE TITLE
display more info at hypershelf pages

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#312]
We would like hypershelf pages to display a bit more information for users by implementing the following changes:

1. Display the About.md file for the corpus and the bottom of the page.

2. Add an "About this corpus" link just below the corpus title similar to the main page (see, e.g., https://www.hypershelf.org/sep/) and also include the "Back to top" link at the bottom.

3. Just beneath or alongside the "About this corpus" link (whichever looks best), include this message: "Click ? button at bottom left for help with the topic explorer interface."

**Comment by kirtansakariya** [comment]
Issue resolved with Pull Request #315
