### ISSUE TITLE
autocomplete not working at hypershelf pages

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#316]
Not working at main page: https://www.hypershelf.org/
Not working at model pages, e.g. https://www.hypershelf.org/sep/60/

It is working in the document section of corpus pages, e.g. https://www.hypershelf.org/sep/

The pattern holds for other hypershelf instances, such as ap, etc.

**Comment by JaimieMurdock** [comment]
Which browser? Main page is working. Model pages are not. Issue is with relative path -- needs to be referencing `../docs.json` rather than `/docs.json`

**Comment by colinallen** [comment]
Yep, main page working for me too now. 

So, just the model pages.  How did path get changed?
