### ISSUE TITLE
NoOptionError after upgrade

### ISSUE THREAD

**Issue by oguzhanalasehir** [inpho/topic-explorer#317]
Hello,
I'm using Windows 7 and Python 2.7.14 :: Anaconda.
I have just updated topicexplorer version as 1.0b214-1-g06a83c5 and later on I got the following error while importing corpus ( from corpus import *);

NoOptionError                             Traceback (most recent call last)
<ipython-input-1-01f24724915d> in <module>()
----> 1 from corpus import *

C:\Users\ENF_RP\Desktop\deneme\notebooks\corpus.py in <module>()
     25 else:
     26     c = Corpus.load(config.get('main', 'corpus_file'))
---> 27 context_type = config.get('main', 'context_type')
     28 ctx_metadata = c.view_metadata(context_type)
     29 all_ids = ctx_metadata[doc_label_name(context_type)]

C:\Users\ENF_RP\Anaconda2\lib\site-packages\backports\configparser\__init__.pyc in get(self, section, option, **kwargs)
    801         except KeyError:
    802             if fallback is _UNSET:
--> 803                 raise NoOptionError(option, section)
    804             else:
    805                 return fallback

NoOptionError: No option 'context_type' in section: 'main'

Could you please help me about the issue?

Best regards,

**Comment by JaimieMurdock** [comment]
Would it be possible to include the `.ini` file associated with your `notebook` instance? 

When there is not a `context_type`, often that indicates that the LDA models have not yet been trained.

Regardless, it should not error in this user-unfriendly way, so a more helpful message will be included :)

**Comment by oguzhanalasehir** [comment]
I attached the ini file
[pure_terms.zip](https://github.com/inpho/topic-explorer/files/2040230/pure_terms.zip)

Btw,I checked training process again and I realized that it produced a warning as given below.

Traceback (most recent call last):
  File "C:\Users\ENF_RP\Anaconda2\Scripts\topicexplorer-script.py", line 11, in
<module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "c:\windows\system32\topicexplorer\topicexplorer\__main__.py", line 243,
in main
    benchmark(train.main)(args)
  File "c:\windows\system32\topicexplorer\topicexplorer\train.py", line 243, in
main
    os.remove(cluster_path)
TypeError: remove() argument 1 must be string, not None

**Comment by JaimieMurdock** [comment]
The error has been fixed in github, but is not yet in a release. I should be able to push that in the next 2 hours.

**Comment by JaimieMurdock** [comment]
Also, because of that error, the train hadn't been working, so I also pushed a change to that.

**Comment by JaimieMurdock** [comment]
The issues should be fixed in the releases as well now

**Comment by oguzhanalasehir** [comment]
Thank u Jaimie, it is OK. 

Best regards
