### ISSUE TITLE
return utf8 in chinese search box

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#328]
Topic search for Chinese words not in the corpus results in unreadable feedback at inpho.xjtu.edu.cn/handian.  Works properly at hypershelf.org/handian.

![image](https://user-images.githubusercontent.com/705195/41209120-feaf008a-6d5b-11e8-83a9-5bf308a15049.png)

**Comment by JaimieMurdock** [comment]
I remember fixing this earlier. Ensure `topicexplorer` is up to date. Has been a repeated issue.
