### ISSUE TITLE
Merge ports to single in-page model switch

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#37]
Animate reordering when switching from 20-topics to 40, 60, etc.

**Comment by JaimieMurdock** [comment]
Some progress was made in the new `launch.py` script, which enables all ports to be started and stopped at once. One possible stop-gap is using that to host a single port which routes requests to the proper private port.

**Comment by JaimieMurdock** [comment]
This is almost done on the [mod_wsgi](https://github.com/inpho/topic-explorer/tree/mod_wsgi) branch.
