### ISSUE TITLE
keeping topic focus with change of K

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#45]
Changing the number of topics with blank document box when in ?topic= mode should retain topic-centered focus and not load up a document-centered view.

**Comment by JaimieMurdock** [comment]
This project has been picked up by Adithya.

**Comment by JaimieMurdock** [comment]
Going to mark this as won't fix for now - we need to figure out how to tackle topic alignment more generally, but the cluster view resoled many of the immediate concerns.
