### ISSUE TITLE
train script - file names with spaces

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#63]
Train script fails at launch.py final step when filename has spaces in it -- should escape spaces with \

**Comment by colinallen** [comment]
also browser launch seems to fail in case where directory name contains spaces

**Comment by JaimieMurdock** [comment]
Try launching the filename in quotes, does this work?

**Comment by colinallen** [comment]
The code appeared to execute, but the web browser did not auto-launch and a direct attempt to enter localhost:port into browser returned “Server not responding”

(This was Justin’s work — for the time being he is going to rerun without spaces.)


On Mar 12, 2015, at 10:10, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:

Try launching the filename in quotes, does this work?

**Comment by JaimieMurdock** [comment]
The launch.py script still doesn't handle errors as gracefully as it 
should. In particular, I do not autoassign ports, and the default is 
just to put a port range of 16xxx, modifying the ini script might help 
with that. Another thing is to check if a server is already running "ps 
ax | grep server.py" to see running instances. The logs can be seen in 
"TOPEX_HOME/logs/CORPUS_NAME/K.log" where all the caps are variables.

**Comment by colinallen** [comment]
ok - I’ve forwarded this to Justin and asked him to follow the issue and contribute further info.

On Mar 12, 2015, at 2:00 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:

The launch.py script still doesn't handle errors as gracefully as it
should. In particular, I do not autoassign ports, and the default is
just to put a port range of 16xxx, modifying the ini script might help
with that. Another thing is to check if a server is already running "ps
ax | grep server.py" to see running instances. The logs can be seen in
"TOPEX_HOME/logs/CORPUS_NAME/K.log" where all the caps are variables.

**Comment by jstamets** [comment]
I've rerun all of the steps, this time without the spaces in the file name (pardon me). This time I was directed from the terminal to the website. It appears that there has been some issue with the text files I have created. I'm being told that the documents are invalid. I used the script you sent me to modify the original txt files, but something appears to have gone wrong.

**Comment by colinallen** [comment]
This usually means a problem with the vsm version you are using. Try a git pull in your vsm directory and then make sure to run the setup script.


--
http://mypage.iu.edu/~colallen/

On Mar 12, 2015, at 18:59, jstamets <notifications@github.com<mailto:notifications@github.com>> wrote:


I've rerun all of the steps, this time without the spaces in the file name (pardon me). This time I was directed from the terminal to the website. It appears that there has been some issue with the text files I have created. I'm being told that the documents are invalid. I used the script you sent me to modify the original txt files, but something appears to have gone wrong.

**Comment by JaimieMurdock** [comment]
This issue has been silent for over 2 months. Was it resolved?

**Comment by JaimieMurdock** [comment]
Definitely still broken.

**Comment by JaimieMurdock** [comment]
This has been fixed.
