### ISSUE TITLE
allow vsm train to continue from previous training iterations

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#74]

**Comment by JaimieMurdock** [comment]
In progress, had to fix random seed issues in #107 first.

**Comment by JaimieMurdock** [comment]
Fixed random seeds, now need to add boolean prompt to `vsm train`.

**Comment by JaimieMurdock** [comment]
Started adding continue training functionality. Still have several things to do:
- [ ] fix `vsm` progress bars to show only number of iterations left to train, not including original iterations.
- [ ] change prompt for number of iterations to explicitly ask for *total* iterations in the continue training case.
- [ ] add min and max to `topicexplorer.lib.util.int_prompt`

**Comment by JaimieMurdock** [comment]
Running continue once works correctly, but twice breaks with:

```python
TypeError: Argument 'mtrand_str' has incorrect type (expected str, got numpy.ndarray)
```

This is due to the second load occuring with LdaCgsSeq rather than LdaCgsMulti.

**Comment by JaimieMurdock** [comment]
Fixed!
