### ISSUE TITLE
Alphabetization not working

### ISSUE THREAD

**Issue by hannahroseeli** [inpho/topic-explorer#82]
Go to http://inphodata.cogs.indiana.edu:19020/?doc=v2.62.LETTER_LXIII.--TO_JOHN_ADAMS%2C_July_1%2C_1787.txt

Click "Alphabetical sort" and notice that the documents are not sorted alphabetically.

**Comment by JaimieMurdock** [comment]
Painfully simple error - the `alphabetSort` function is using the `id` field rather than the `label` field. Fixing now in index.mustache.html
