### ISSUE TITLE
"Close" button not appearing in reduced window

### ISSUE THREAD

**Issue by hannahroseeli** [inpho/topic-explorer#83]
When viewing a document in the topic model at less than full screen, the button to "Close" the document does not appear and cannot be scrolled to. 

1. Select a document and visualize it at any granularity. 
2. Open any document in the list by clicking on the small book icon to the left of the document's name. 
3. Shrink your browser window to approximately 3/4 size of the full browser
4. Attempt to close the document by pressing the blue "Close" button that typically appears when attempting to close a document. 
5. Notice the inability to find said button or scroll to it

**Comment by JaimieMurdock** [comment]
The escape key and clicking the new "x" on top of the modal will both close the window now, no matter the size.
