### ISSUE TITLE
Words in search bar not being visualized

### ISSUE THREAD

**Issue by hannahroseeli** [inpho/topic-explorer#87]
To find this, go to the TJmind homepage and type "religion" into the main search bar. Then, select the 60 topic model. 

When I do this, one of two things happens. 
1. A random letter pops up and is analyzed (I wasn't able to replicate this one, so it's possible that this was just something that happened as a fluke)
2. Nothing. When I click the "60 Topics" area in the dropdown menu, the button still displays "Visualize" and the screen doesn't change. 

Is this a browser/cache clearing issue?

**Comment by colinallen** [comment]
Looks like a problem on the TJMind splash page only. (I’m seeing behavior 2.)

Works as expected at http://inphodata.cogs.indiana.edu:19060

**Comment by JaimieMurdock** [comment]
http://tjmind.org/ now no longer allows arbitrary typing, and bars interface doesn't either, so bug is now invalid!
