### ISSUE TITLE
May there be a version for R

### ISSUE THREAD

**Issue by ip1200** [inpho/topic-explorer#88]
I hope this powerful tool can be available on R.

**Comment by JaimieMurdock** [comment]
Glad to hear from you.

There is an interop module under development that will allow import of topic models trained with the [R `topicmodels` package](https://cran.r-project.org/web/packages/topicmodels/index.html), alongside [lda-c](http://www.cs.princeton.edu/~blei/lda-c/) and [MALLET](http://mallet.cs.umass.edu/).

I'm not as familiar with the R ecology, is `topicmodels` the package to use or is there another package that would be helpful to import from?

**Comment by ip1200** [comment]
topicmodels (package) is what I used, and there are lda (package) but I haven't tried.
