### ISSUE TITLE
`vsm init` from within folder raises invalid path issue.

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#91]
[140-182-185-34:~/corpora/Chinese/Confucianism] colin% vsm --version
1.0b39-0-g16fbed7
[140-182-185-34:~/corpora/Chinese/Confucianism] colin% ls Analects-20
.       liren.txt   weizheng.txt    xueer.txt   zihan.txt
..      models      weizi.txt   yanghuo.txt zilu.txt
bayi.txt    shuer.txt   xiangdang.txt   yanyuan.txt zizhang.txt
gongyechang.txt taibo.txt   xianjin.txt yaoyue.txt
jishi.txt   weilinggong.txt xianwen.txt yongye.txt
[140-182-185-34:~/corpora/Chinese/Confucianism] colin% vsm init Analects-20/

Corpus Name [Default: Analects-20] 

Corpus file found. Rebuild? [y/N] y
Building corpus from Analects-20/
Detected 1 folders and 20 files in Analects-20/
ERROR: invalid path, please specify either:
- a single plain-text file,
- a folder of plain-text files, or
- a folder of folders of plain-text files.

Exiting...

**Comment by colinallen** [comment]
PS -- also does the same thing when --unicode flag is specified, but works ok on a folder of English/ascii txt files

**Comment by JaimieMurdock** [comment]
It is finding both folders and files in Analects-20, so doesn't know whether to create a collection corpus or a directory corpus. This needs a better error message, so I'm leaving the issue open.

Towards debugging your specific error: Does Analects-20 have a hidden subdirectory in it?

**Comment by JaimieMurdock** [comment]
Issue here is that you ran `vsm init` from within the Analects20 folder instead of outside of it. This means the `models` directory was put inside the Analects20 folder, so it choked.

Might be useful to pre-diagnose this in the IOError exception handler.

**Comment by JaimieMurdock** [comment]
The new method of importing corpora solves this problem - it is just doing a recursive walk through all files now.
